language: cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # g++
    - sudo add-apt-repository -y ppa:h-rayflood/llvm # clang
    - sudo apt-get update -qq
      #- curl https://gforge.inria.fr/frs/download.php/33525/CGAL-4.4.tar.gz | tar zxv
      #- (cd CGAL-4.4; CXXFLAGS=-fPIC cmake -DBUILD_SHARED_LIBS=FALSE .; make CGAL)

install: 
    - sudo apt-get install libboost-dev libboost-program-options-dev
      #- sudo apt-get install libcgal-dev libgmp3-dev
    - sudo apt-get install libgmp3-dev cmake
    # The next 4 lines download the CGAL tarball, but this requires cmake
    # 2.8.11, yet travis has only 2.8.7
    - wget https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.7/CGAL-4.7.tar.gz
    - tar -xzvf CGAL-4.7.tar.gz
    - cd CGAL-4.7
    - cmake .
      # force g++ compiler versions, but this is not necessary for clang
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

#env:
#    global:
#        CGAL_GYP_LDFLAGS: -L$TRAVIS_BUILD_DIR/CGAL-4.4/lib
#        CGAL_GYP_INCLUDES: $TRAVIS_BUILD_DIR/CGAL-4.4/include
#        matrix:
#            -
#            - GGAL_USE_EPECK=1

script: 
    - cd ./build
    - cmake ..
    - make
